### ISSUE TITLE
waiting for transaction long time still not in my wallet

### ISSUE THREAD

**Issue by webmacho** [stacksgov/stacks-co#10]
transaction was sent from my binance account to hiro wallet https://explorer.stacks.co/txid/0xa7b612f75fd5577fad4d6583495763c294bdd4dd0e906874d5583806a0bc5601?chain=mainnet

nothing there and ond binance for hours 0/6 confirmations why?

**Comment by cuevasm** [comment]
Not relevant to this repo, you need to contact Binance for an issue with their exchange.
