### ISSUE TITLE
Homepage link - Videos

### ISSUE THREAD

**Issue by MikeD123** [stacksgov/stacks-co#11]
The link for videos goes to - https://www.youtube.com/user/Stacks

This has something called "Callnowbutton" all over the channel. I was looking for some explainers/high-level intro's to grok the Stacks ecosystem, but it led me to this.

Is there an official Stacks channel? Or is it tbd?

Just flagging this in case it wasn't already known! Thank you!

**Comment by cuevasm** [comment]
Sorry, not seeing any links to that, perhaps the team has already updated this. Everything I can find links to the proper place, which is: https://www.youtube.com/c/Blockstack/videos
