### ISSUE TITLE
Stacks Indonesia

### ISSUE THREAD

**Issue by empeje** [stacksgov/stacks-co#12]
Hi Team,

We are from Stacks Indonesia community who currently applying for grants for local chapter. I'd like to have our community listed on the ecosystem page.

Here's our Twitter https://twitter.com/stacksindonesia

**Comment by cuevasm** [comment]
Thank you! Please reopen this issue once your Chapter grant has been approved, we can't add you before that. 😁

**Comment by empeje** [comment]
Hi @cuevasm our chapter is approved now and running last January, can we get listed in the site?
