### ISSUE TITLE
100 STX not receive in the Blockchian wallet

### ISSUE THREAD

**Issue by salmanmohsin333** [stacksgov/stacks-co#13]
Sir 
i apply in the STX airdrop last year the 1000 coin in awards to me but the amount not credited in the account
i contact the support alot of time they told me that in the end of 2021  the amount is credited in your account 

Now after the end of the year 2021  the tranaction is not in the Rewards airdrop account

Could you please update of the the issue i have in the account 
![Screenshot 2021-09-18 214214](https://user-images.githubusercontent.com/43271923/149654144-75b787f9-052d-4139-9d50-bde67d11baf3.jpg)

**Comment by cuevasm** [comment]
Not relevant to this repo. Please reach out to Blockchain.com support, we have no control over their systems.
