### ISSUE TITLE
Copy Edit on "Start Staking" Page

### ISSUE THREAD

**Issue by sjwhitely** [stacksgov/stacks-co#18]
Request from user to please update copy regarding Xverse having no fees here: https://www.stacks.co/learn/stacking
Xverse does have fees :)
![Screen Shot 2022-02-04 at 2 29 28 PM](https://user-images.githubusercontent.com/98830038/152591611-c6fb504e-a6e8-43dc-a529-6d571962258f.png)

**Comment by cuevasm** [comment]
Xverse does not have any fees
