### ISSUE TITLE
Fix aspect ratio on images on landing page in "Powered by Clarity" section

### ISSUE THREAD

**Issue by 0xAsteria** [stacksgov/stacks-co#2]
Snippets on right are a lil' buggy

<img width="1439" alt="Screenshot 2021-11-20 at 09 17 02" src="https://user-images.githubusercontent.com/67651251/142721101-f95dcb5d-05a8-40ac-92a9-45f787215285.png">

**Comment by TitoSolano-Impulso** [comment]
Let me check this, thanks! Browser?

**Comment by 0xAsteria** [comment]
Safari 15.1, Monterey beta
