### ISSUE TITLE
Website doesn't render correctly on Safari

### ISSUE THREAD

**Issue by janniks** [stacksgov/stacks-co#23]
macOS 12.3
Safari 15.4 (17613.1.17.1.6)

![Screen Shot 2022-03-23 at 16 46 23](https://user-images.githubusercontent.com/6362150/159740036-a99e42e3-9ef2-45e1-954c-51a1d7a7bb2d.png)

**Comment by TitoSolano-Impulso** [comment]
I think is solved now. Can you confirm please. @janniks

**Comment by cuevasm** [comment]
Looks good in all Mac/Safari conbos via Browserstack, closing.
