### ISSUE TITLE
Fix title on stacks.co/learn/introduction

### ISSUE THREAD

**Issue by eugeniadigon** [stacksgov/stacks-co#3]
On https://www.stacks.co/learn/introduction instead of "What is Stacks?" it says "What is Stacking?"

<img width="1381" alt="Screenshot 2021-11-22 at 18 28 30" src="https://user-images.githubusercontent.com/78865845/142937726-add95cf3-1c4e-485f-9fa4-cb2d87b17c5b.png">

**Comment by cuevasm** [comment]
Updated. Will be live on next publish
