### ISSUE TITLE
Broken link in "Stacks 101"

### ISSUE THREAD

**Issue by php4fan** [stacksgov/stacks-co#32]
At https://www.stacks.co/learn/introduction

![image](https://user-images.githubusercontent.com/13969584/168391087-01e1a3e6-eaf0-4a62-a747-448e35c749d9.png)

links to https://stacks.org/stacks-blockchain which is broken:

![image](https://user-images.githubusercontent.com/13969584/168391160-04bcb0ce-4817-4095-a406-8248bdc714be.png)

Literally my 2nd clicks from the homepage.

**Comment by cuevasm** [comment]
Must be a local issue for you, perhaps your network. This link functions normally. Thanks!

https://stacks.org/stacks-blockchain

**Comment by php4fan** [comment]
Yeah it works now, I guess it's fixed.

LOL local issue in my network, causing a 403 forbidden error from the nginx server, right.
