### ISSUE TITLE
typo under Shannon profile

### ISSUE THREAD

**Issue by Hero-Gamer** [stacksgov/stacks-co#35]
- Found a typo in **https://stacks.org/about** page 
- Under Shannon's profile
- should says Blockstack instead of Blocktack

<img src="https://user-images.githubusercontent.com/92864860/169315835-a7a902c9-2a74-4d1e-8f12-2a30d01d4f50.jpg" width="280px" />

Thanks.

**Comment by cuevasm** [comment]
Thanks, but that would be accurate as that's what it was called at the time and what people externally know those events for.
