### ISSUE TITLE
Include app on Stacks website

### ISSUE THREAD

**Issue by GremlinOnTheComputer** [stacksgov/stacks-co#40]
Requesting that the LaunchMyNFT launchpad site is included here: https://www.stacks.co/explore/discover-apps#apps

LaunchMyNFT website/app is here: https://launchmynft.io/

Requesting because it is a multi-chain, permission-less NFT collection generation and creation program that has support for Stacks NFTs. It would be great to let the Stacks community know they have this option when making NFTs on Stacks.

**Comment by cuevasm** [comment]
Please submit the application using the form on the website: https://www.stacks.co/add-an-app
