### ISSUE TITLE
Access to pDrive app deprecated

### ISSUE THREAD

**Issue by nmarkfox** [stacksgov/stacks-co#41]
Moving from Blockstack to Stacks leaves me no access to files I've stored on the pDrive app.  Please provide instructions on how to recover this information.

**Comment by cuevasm** [comment]
Hey there, this isn't a support channel. I recommend reaching out to the creator of the application if you can. The good news is that your files will not have been stored 'in pDrive', they are stored in Gaia, a decentralized storage provider that is encrypted by your private key, so you should be able to access those files using another application or the command line.

This hasn't come up that I'm aware of so I assume people have found solutions, I'm just not personally aware of them. You can jump into the forum thread I posted on your behalf and see what advice others have. 

https://forum.stacks.org/t/best-way-to-interact-with-gaia-files-uploaded-managed-by-now-defunct-applications/13462
