### ISSUE TITLE
Add NeoSwap to the Discover Apps Section

### ISSUE THREAD

**Issue by empeje** [stacksgov/stacks-co#42]
Hi I want to report two things

- I want to add NeoSwap (https://neoswap.party/#/home) the Cohort 2 Alumni of Stacks Accelerator that is graining significant traction over the past few months.
- I also discover the "[Submit a Stacks App](https://www.stacks.co/add-an-app)" link is dead in here https://www.stacks.co/explore/discover-apps -> https://www.stacks.co/add-an-app
- Lastly is it possible to include all the Stacks Accelerator Apps in the Discover app section, assuming they already done the integration with Stacks?

Thank you

**Comment by cuevasm** [comment]
- Hey there, please have the founders of NeoSwap submit their app using the site (see item #3 for why we haven't added it)
- The link is not dead, it resolves to the form - https://www.stacks.co/add-an-app
![image](https://user-images.githubusercontent.com/6131188/181267460-e71381c0-fff1-4cdb-bf24-6f0090b18a55.png)
- App creators can use the form to submit their posts, some teams prefer to wait until a launch moment or are in stealth, so we don't list them without contact from them.
