### ISSUE TITLE
Add Transak to Buy STX

### ISSUE THREAD

**Issue by sure-win** [stacksgov/stacks-co#44]
Sherwin here from Transak.  We already work closely with your partners at Hiro and wanted to see if there's an opportunity to be added as an additional on ramp provider.   

Our rates are very competitive about 5% better or more depending on the currency.   We also have the most local payment methods available example AstroPay in Brazil and Mexico, UnionPay in Asia and lots more.  It would be great to let the Stacks community know they have options that suit their local preferred payment needs.

We pride on being developer focused so you can see how easy the integration is https://transak.gitbook.io/transak-docs/

<img width="1065" alt="Screen Shot 2022-08-30 at 10 56 40 PM" src="https://user-images.githubusercontent.com/112530141/187607013-cd750f34-41e4-4652-9e29-93542e87a3ca.png">

**Comment by stackinjack** [comment]
Sure, Transak has been added to the STX page: https://www.stacks.co/explore/get-stx#getstx
