### ISSUE TITLE
Xverse listings

### ISSUE THREAD

**Issue by aliceincrypt0land** [stacksgov/stacks-co#45]
On this page https://www.stacks.co/explore/discover-apps, please change description to "Advanced Bitcoin wallet enabling non-custodial Stacking pool and more." Also update the website link to https://www.xverse.app/ and Twitter link to https://twitter.com/xverseApp.

On the stacking page https://www.stacks.co/learn/stacking, Xverse pool should link to here: https://pool.xverse.app/.

In this listing, please update "Connect to Blockchain apps" to "Connect to Bitcoin Web3 apps" https://www.stacks.co/explore/find-a-wallet. 

Thank you!

**Comment by cuevasm** [comment]
Made the changes we could, the URL was already what you requested and the description we edited slightly for clarity/brevity.
