### ISSUE TITLE
forgot to put MEMO when sending STX from BLOCKCHAIN ​​to BINANCE

### ISSUE THREAD

**Issue by Mirull98** [stacksgov/stacks-co#46]
Hello STACKS, i forgot to put MEMO when sending from BLOCKCHAIN ​​to BINANCE, and I still haven't received coins on binance
![C4734A5A-E16B-4550-90B4-282AE21FCD2E](https://user-images.githubusercontent.com/116482135/197379176-9ab4fdc6-6148-4725-a8ef-b9bbaf622d69.png)
![Uploading 4C21E1FB-B728-4130-9095-D640114CA714.png…]()

**Comment by cuevasm** [comment]
For help with an exchange related transaction, please contact the exchange.
