### ISSUE TITLE
More Clarity in Browse Talent Page

### ISSUE THREAD

**Issue by SamAbiodun** [stacksgov/stacks-co#49]
It would be better if the talent's roles were displayed on their profile without needing to click on them.
It's very stressful to be on the lookout for promising talent but you have to individualy click them to see what they do.

<img width="1581" alt="Screenshot 2023-01-08 at 00 50 30" src="https://user-images.githubusercontent.com/81042468/211174465-4641bf51-2bb5-4422-9aaa-4f98b9b2f9da.png">

**Comment by cuevasm** [comment]
Thanks Sam, this job board is an embed from HireVibes, so we can't really control it to that level, but we've made similar suggestions to the team in the past and are hopeful they'll add some filtering like that in the near future.

**Comment by SamAbiodun** [comment]
Hi Sean, thank you for the update. It's great to know it's being worked on.
