### ISSUE TITLE
BTC stuck on chain

### ISSUE THREAD

**Issue by clevelander** [stacksgov/stacks-co#51]
Hey my BTC got stuck sending BTC from Hiro to Sparrow. 
I need help retrieving my BTC from Hiros please!!!

https://mempool.space/tx/33fcd296f6180e66428f8fc744e0180894a70447ffb53fd39490613a8e75f87c

**Comment by cuevasm** [comment]
This is not the place for support with this, please reach out to Hiro or Sparrow
