### ISSUE TITLE
OkCoin no longer offers stacking.

### ISSUE THREAD

**Issue by BeyersNel** [stacksgov/stacks-co#53]
https://blog.okcoin.com/blog-stacks-stx-and-citycoins-mia-and-nyc-stacking-options/

**Comment by cuevasm** [comment]
Yep and it was removed from the site. If you're still seeing it somewhere please clear your cache and if you still see it, provide a URL/screenshot. Thanks!

**Comment by BeyersNel** [comment]
Website seems fine now. Thanks!
