### ISSUE TITLE
Help related to the CityCoin platform

### ISSUE THREAD

**Issue by Hunbelede** [stacksgov/stacks-co#56]
Please help me I have a problem with the CityCoin platform, New York city coin. The problem is that I have earned rewards and I cannot withdraw them. I was in contact with the people of city coin on Discord and they told me that it is a problem with the API ( my wallet has lost integracion to cictcoin due to an API key error which caused the error even you try to claim you rewards). I can't find the message you wrote to me, it's deleted. He sent me a link to restore the wallet on the blockchain and I had to put the seed phrases and an error appeared. Then he told me that if I put 1000 dollars in the hiro wallet it can be recovered and if I put 10 dollars it won't work. I have the impression that it is a scam. Page is betadigital.site  select Asset Recovery. I have screenshots if you need. The name of the user with whom I was in communication and telling me that he can help me, changes every day. Thanks for reading this message.

**Comment by cuevasm** [comment]
Hey there, this is a repo related to the Stacks website which has no relationship with CityCoins. You should join the CityCoins Discord and find support there: https://discord.com/invite/shZ5Zv4xSP
