### ISSUE TITLE
Roadmap section on stacks.co leads to a broken link.

### ISSUE THREAD

**Issue by andrerserrano** [stacksgov/stacks-co#57]
Roadmap section on stacks.co leads to a broken link. 

<img width="872" alt="Screen Shot 2023-08-03 at 7 36 35 AM" src="https://github.com/stacksgov/stacks-co/assets/44974743/85354664-2d10-42c2-9f6f-accb7f2e8225">
<img width="862" alt="Screen Shot 2023-08-03 at 7 36 46 AM" src="https://github.com/stacksgov/stacks-co/assets/44974743/6f8b618a-04d8-4481-b3e8-4446068422a2">

**Comment by ivoandov** [comment]
This has been fixed. Thanks for reporting the bug!
