### ISSUE TITLE
Lots of links have an extra long line

### ISSUE THREAD

**Issue by eugeniadigon** [stacksgov/stacks-co#6]
Line should be the width of the text

<img width="1370" alt="Screenshot 2021-11-22 at 18 34 04" src="https://user-images.githubusercontent.com/78865845/142938399-b64eb4b8-965b-4801-8904-411d8fc2a473.png">

<img width="1266" alt="Screenshot 2021-11-22 at 18 37 06" src="https://user-images.githubusercontent.com/78865845/142938835-2d11e658-282d-4eab-a1ca-685dfa544af4.png">

**Comment by TitoSolano-Impulso** [comment]
Is fixed, and I will work on a button system that can be more easy to update.
