### ISSUE TITLE
Broken link on homepage footer

### ISSUE THREAD

**Issue by craegandreessen** [stacksgov/stacks-co#67]
The "Roadmap" button in the footer of the page links to:

https://www.stacks.co/roadmap-old-v2

Which is a link to a page that has been moved or deleted.

**Comment by craegandreessen** [comment]
The correct link I blieve should be.

https://www.stacks.co/roadmap

**Comment by nickglu86** [comment]
+1 , I also noticed this issue, the correct link you mentioned is the one given by google
