### ISSUE TITLE
Update Planbetter Pool's data

### ISSUE THREAD

**Issue by planbetterHQ** [stacksgov/stacks-co#74]
Could you modify the data of our pool in https://www.stacks.co/learn/stacking ?
We'd like it to have it like this: `Non-custodial • BTC • 200 STX min • 5% fee`

Please, update our logo with this version in HD
![PlanbetterRoundedLogo-icon-black](https://github.com/stacksgov/stacks-co/assets/89087989/4ef6a5c2-418d-45a5-b208-d090fcdf2891)

**Comment by planbetterHQ** [comment]
@cuevasm the updated text doesn't much what we asked. It doesn't fit in one line as we expected. Could you review it again? 
![image](https://github.com/stacksgov/stacks-co/assets/89087989/88196036-7e8d-4a46-82e7-ca0fafd70dca)

**Comment by cuevasm** [comment]
Hey, the text is exactly what was asked for, except we standardized it with the way others are listed. The sizing is dynamic, there's no way it'll fit on one line on every device. Can you tell me why the single line is a concern? Your text is roughly the same length as everyone else's. 

![Screenshot_20240228-085557.png](https://github.com/stacksgov/stacks-co/assets/6131188/b7046b14-95a7-44c8-a79f-3b368efe4764)

**Comment by cuevasm** [comment]
Hey, the text is exactly what was asked for, except we standardized it with the way others are listed. The sizing is dynamic, there's no way it'll fit on one line on every device. Can you tell me why the single line is a concern? Your text is roughly the same length as everyone else's.  
 

![](https://github.com/stacksgov/stacks-co/assets/6131188/2757c0ad-8afe-4032-8963-2fb425a8ce1d)

**Comment by planbetterHQ** [comment]
It wasn't standardised, when we reviewed this morning. It makes sense now. Thanks for the update!
