### ISSUE TITLE
Secure staking with ledger

### ISSUE THREAD

**Issue by tradehusen** [stacksgov/stacks-co#75]
It would be great, if you could reach out to Ledger to implement a secure staking mechanism in their hardware wallets.

**Comment by cuevasm** [comment]
Thanks for the suggestion, you can already use Ledger hardware wallets for Stacking. Look into the Leather wallet: [https://leather.io/](https://leather.io/). Eventually, there will be a native Ledger Live option too, but Leather is the most popular wallet in the ecosystem and supports Ledger today. Next time please make suggestions like this on the Stacks forum, this repo is not a protocol request area, it's for the website. You can also start a SIP or Working Group to move forward things you believe are important.
