### ISSUE TITLE
Update Charisma App on Ecosystem Page

### ISSUE THREAD

**Issue by r0zar** [stacksgov/stacks-co#77]
Name: Charisma
Description: You decide the tokenomics, governance, and future of Charisma. Join the community-run DAO.

Website: https://www.charisma.rocks/
Twitter: https://twitter.com/CharismaBTC
Discord: https://discord.gg/ZWhdQmZcdy
Github: https://github.com/pointblankdev/dungeon-master
Category: DAO

Also- SIP10 token Charisma (CHA) can be added to tokens section
Description: Governance token of the Charisma DAO

**Comment by r0zar** [comment]
THANK YOU !

**Comment by cuevasm** [comment]
Hey, in the future you can use the form that's on the ecosystem page to submit updates to listings or new listings. Makes it much easier on us, thanks! Just click 'Add Something' there at the top 🙏
