### ISSUE TITLE
Font sizes are smaller/different than should be in some sections

### ISSUE THREAD

**Issue by eugeniadigon** [stacksgov/stacks-co#8]
Not really how to address this since it's a recurrent issue in multiple parts of the site, but I can exemplify with one comparison:

https://www.stacks.co/learn/introduction

Figma: https://www.figma.com/proto/LEQbuBih8blGEcQHfYlQ0T/Stacks.co-Redesign?node-id=757%3A6214&scaling=min-zoom&page-id=632%3A1211

**Comment by TitoSolano-Impulso** [comment]
Hi! I´ll do a complete review and set up of the headings and texts, because yes something went a bit lost at some point with the fonts
