### ISSUE TITLE
Where can I see the decimals of the Token

### ISSUE THREAD

**Issue by sefigi** [stacksgov/stacks-co#82]
1. Where can I see the decimals of the Token, 
2. how is the contract displayed on Stacks explorer the same as the contract details?
3. SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin Why is the total supply of tokens 123B?
![image](https://github.com/stacksgov/stacks-co/assets/44665855/a218023a-9b01-4f2d-857e-ff032d851392)

**Comment by cuevasm** [comment]
Hey @sefigi - please reach out to the maintainers of the Explorer for questions regarding the Explorer. The contact information is there in the footer of any page. You can either message for support or open an issue with them:

- [Support](https://explorer.hiro.so/support)
- [Submit bug or feature request](https://github.com/hirosystems/explorer/issues/new/choose)
