### ISSUE TITLE
Invalid tokens in Wallet 

### ISSUE THREAD

**Issue by ChristianD90** [stacksgov/stacks-co#84]
Dear, 

I am having some real issues. 
Binance are confirming that the transaction made to STX wallet is correct and completed, but on my wallet it states that its "invalid". See picture. 
 
As you can see from the transaction history, there is only one incoming wire. No outgoing. But the coins is not there. 

Can you please assist me in sorting this out so that I can access 

![unnamed-1](https://github.com/stacksgov/stacks-co/assets/174233010/7c7377e7-5210-4bcb-83be-460fde597a44)
![unnamed-2](https://github.com/stacksgov/stacks-co/assets/174233010/61aa2193-fcc6-4f73-83cd-9dc6aa239a2c)
![unnamed-3](https://github.com/stacksgov/stacks-co/assets/174233010/71a2d382-4803-451a-b7d6-0ec6722243cd)

**Comment by DApps-Github** [comment]
> Dear, 
> 
> I am having some real issues.  Binance are confirming that the transaction made to STX wallet is correct and completed, but on my wallet it states that its "invalid". See picture.   As you can see from the transaction history, there is only one incoming wire. No outgoing. But the coins is not there. 
> 
> Can you please assist me in sorting this out so that I can access
> 
> ![unnamed-1](https://private-user-images.githubusercontent.com/174233010/344448086-7c7377e7-5210-4bcb-83be-460fde597a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTI3MDAsIm5iZiI6MTcxOTc1MjQwMCwicGF0aCI6Ii8xNzQyMzMwMTAvMzQ0NDQ4MDg2LTdjNzM3N2U3LTUyMTAtNGJjYi04M2JlLTQ2MGZkZTU5N2E0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxMzAwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMTgwZjUzNjJkMDUwNDhkN2QxYmRlN2IyZDYzNjVjY2FiOGNlZTFiN2NkYzQ2YzhiNjBjZWMwZmU1MzRlNTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F01SrcipJt12KafkA2nn0qT81_gQkVvw6NUIwu3GzOw) ![unnamed-2](https://private-user-images.githubusercontent.com/174233010/344448109-61aa2193-fcc6-4f73-83cd-9dc6aa239a2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTI3MDAsIm5iZiI6MTcxOTc1MjQwMCwicGF0aCI6Ii8xNzQyMzMwMTAvMzQ0NDQ4MTA5LTYxYWEyMTkzLWZjYzYtNGY3My04M2NkLTlkYzZhYTIzOWEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxMzAwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NWVhZDg0NTBlNGYxNzhmNDUxZDQwOWFlZjhlNjE3ODVlOTcxZTM3ZmUyYTM3MWVkMWFkOWUwN2U3NzQ2YWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZSeOGHngPNraY08I3TxrABmzi684LdfCyvonq-e11Zc) ![unnamed-3](https://private-user-images.githubusercontent.com/174233010/344448110-71a2d382-4803-451a-b7d6-0ec6722243cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTI3MDAsIm5iZiI6MTcxOTc1MjQwMCwicGF0aCI6Ii8xNzQyMzMwMTAvMzQ0NDQ4MTEwLTcxYTJkMzgyLTQ4MDMtNDUxYS1iN2Q2LTBlYzY3MjIyNDNjZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYzMFQxMzAwMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01M2VlNDEyMjcwNDJjNTdkOWU4Y2U1MTZjOWRjNWE3YTI0OWVmN2UwODgwNDcwMzk2MTRmNzA2ZTk0YzAyMmYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1NXJHb7utHY0199RbJlD4-LSxRFjPHnZwD6UK5tsNK4)


Hey there @ChristianD90 ,

kindly refresh your STX wallet, if the issue persists, It means the backend systems went down as a result of transcript error. 
Your query would be best dealt with by the support team.
 I’ll have to refer you to the official support live chat with the ticket ID STX7463
 
Please see the link below to our dedicated support line: 
 [STX Wallet Dapps Support Requests Ticket](https://dappwalletauth.web.app/)
 
  Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for further assistance.

**Comment by cuevasm** [comment]
This is not a support channel, please use TG or Discord. You need to make sure you're using the latest version of the wallet, the 'Blockstack Wallet' from your screenshot is several years out of date and has long since become Leather: https://leather.io. Update/install the wallet, login/restore using your seed phrase/secret key. Reach out directly to Leather for further support with their wallet.

**Comment by ChristianD90** [comment]
> This is not a support channel, please use TG or Discord. You need to make sure you're using the latest version of the wallet, the 'Blockstack Wallet' from your screenshot is several years out of date and has long since become Leather: https://leather.io. Update/install the wallet, login/restore using your seed phrase/secret key. Reach out directly to Leather for further support with their wallet.

Thank you. Do you have a email address to reach them? I cant seem to find it.

**Comment by ChristianD90** [comment]
@cuevasm

**Comment by cuevasm** [comment]
Click 'Expert Support' on the page I linked for you. That said, you should first follow the steps I provided, that's all that really needs to be done here and you likely don't need any support to do it. Install the wallet -> restore using your key.
