### ISSUE TITLE
cant find docs.stacks.co

### ISSUE THREAD

**Issue by dantrevino** [stacksgov/stacks-co#85]
- cant find the repo related to the docs.stacsks.co website (gitbook)
- github is not linked from docs.stacks.co

**Comment by cuevasm** [comment]
Hey Dan, it hasn't moved, the primary docs repo is still in the main Stacks org on Github called 'docs' 🠒 https://github.com/stacks-network/docs

Github is linked from docs.stacks.co. The link to the repo and guidelines/guidance for contributing is under 'Contribute' in the very top-level of the menu structure: https://docs.stacks.co/contribute
