### ISSUE TITLE
Request to include CoinLedger under the "Taxes" category on the ecosystem page

### ISSUE THREAD

**Issue by lucaswalter** [stacksgov/stacks-co#86]
CoinLedger has a native integration for Stacks which I believe will be valuable for many users with transactions on Stacks and other blockchains.

https://www.stacks.co/explore/ecosystem?category=Taxes#tools

Here are some details about CoinLedger:
- web3 listing on Coinbase: https://www.coinbase.com/web3/dapps/coin-ledger
- website: https://coinledger.io
- X: https://x.com/CoinLedger
- help guide: https://help.coinledger.io/en/articles/9921992-stacks-blockchain-import-guide

![coinledger_icon](https://github.com/user-attachments/assets/6aff2d1a-a589-488d-95f5-5ab777352cb2)

**Comment by cuevasm** [comment]
Hey Lucas, there is a form for submitting an app for consideration by the mods. It is the button at the top of the page you've linked. Once you submit, they'll see it within a week or two, thanks!

**Comment by lucaswalter** [comment]
Missed that - Thanks @cuevasm
